config/routes.rb
MyWedding::Application.routes.draw do

  devise_for :admins, :controllers => { :registrations => "admins/registrations"}
  root 'static_pages#home'
  
  resources :guests do
	put 'complete', on: :collection
  end
  
  match '/invite', to: 'static_pages#invite', via: 'get'
  match '/story', to: 'static_pages#story', via: 'get'
  match '/wish', to: 'static_pages#wish', via: 'get'
  match '/pictures', to: 'static_pages#pictures', via: 'get'
  match '/live', to: 'static_pages#live', via: 'get'
  match '/guests/wish', to: 'guests#show', via: 'get'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/guest.rb
class Guest < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_save :default_value

	validates :name, presence: true
	validates :email, presence: true
	validates :wish, presence: true, length: { maximum: 200 }
	
	
	def default_value
		self.approved ||= true
	end
end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController


def new
	if Admin.all.size > 2
		flash[:notice] = "Admin limit has been reached"
		redirect_to root_path
	else
		super
	end
end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  before_filter :authenticate_admin!, :only => [:index]

  def new
	@guest = Guest.new
  end

  def create
	@guest = Guest.new(guest_params)
	if @guest.save
		flash[:notice] = "Thank you for your wishes! See your message flash on the home screen"
		redirect_to root_path
	else
		render 'new'
	end
  end

  def edit
	@guest = Guest.find(params[:id])
  end

  def update
	@guest = Guest.find(params[:id])
	if @guest.update_attributes(guest_params)
	
		redirect_to root_path
	else
		render 'edit'
	end
 end

  def destroy
	Guest.find(params[:id]).destroy
	flash[:notice] = "Guest deleted."
	redirect_to wish_path
  end
  
  def show
	#@guest = Guest.find(params[:id])
	@guest = Guest.where(approved: true).first(:order => "RANDOM()")
	render :partial => 'static_pages/wishbox'
  end
  
  def index
	@guests = Guest.paginate(:page => params[:page], :per_page => 30)
  end
  
  def complete
	#Guest.update_all()
	
	#Guest.update_all(["approved=?", true], :id => params[:task_ids])
	Guest.where(id: params[:approved_guest_ids]).update_all(approved: true)
	Guest.where(id: params[:disapproved_guest_ids]).update_all(approved: false)
	redirect_to guests_path
  end
  
  def guest_params
	params.require(:guest).permit(:name, :email, :wish)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def story
  end

  def invite
  end

  def wish
	redirect_to new_guest_path
  end
  
  def pictures
  end
  
  def live
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_page_title(this_page_title)

		base_title = "Our Wedding"
		
		if this_page_title.empty?
			base_title
		else
			"#{base_title} | #{this_page_title}"
		end
	end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/guests/create.html.erb
<h1>Guests#create</h1>
<p>Find me in app/views/guests/create.html.erb</p>

app/views/guests/destroy.html.erb
<h1>Guests#destroy</h1>
<p>Find me in app/views/guests/destroy.html.erb</p>

app/views/guests/edit.html.erb
<h1>Guests#edit</h1>
<p>Find me in app/views/guests/edit.html.erb</p>

app/views/guests/index.html.erb

<%= form_tag complete_guests_path, :method => :put do %>
<table>
	<% @guests.each do |guest| %>
		<tr>
			<td><%= guest.name %></td>
			<td><%= guest.email %></td>
			<td><%= guest.wish %></td>
			<td><%= check_box_tag "approved_guest_ids[]", guest.id, guest.approved %></td>
			<td><%= check_box_tag "disapproved_guest_ids[]", guest.id, !guest.approved %></td>
		</tr>
	<% end %>
</table>
<%= submit_tag "Approve" %>
<% end %>
<%= will_paginate @guests %>

app/views/guests/new.html.erb
<div id="container">
<div id="message_form_wrapper">
<%= form_for(@guest) do |f| %>
	<%= render "shared/error_messages" %>
	<h4 class: "form_element">Name*: </h3>
	<%= f.text_field :name, class: "form_element"%>
	<h4 class: "form_element">Email*: </h3>
	<%= f.email_field :email, class: "form_element"%>
	<h4 class: "form_element">Message*: </h3>
	<%= f.text_area :wish, rows: "5", columns: "40", class: "form_element" %>
	<%= f.submit "Send Message", class: "button", id: "form_submit"  %>
<% end %>
</div>
<div id="message_info">
<h4>Look for your message on the home screen! You can also email your messages to josteffwedding_at_gmail.com</h4>
</div>
</div>

app/views/guests/update.html.erb
<h1>Guests#update</h1>
<p>Find me in app/views/guests/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_page_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46390038-1', 'josteffwedding.com');
  ga('send', 'pageview');

</script>
  <link href='http://fonts.googleapis.com/css?family=Engagement' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Maiden+Orange' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag %>
</head>
<body>


<%= render "shared/header" %>
<h1>Our Wedding</h1>

<%= yield %>

<%= render "shared/footer" %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @guest.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@guest.errors.count, "error") %> prevented your entry being saved </h2>
			<ul>
				<% @guest.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>

app/views/shared/_footer.html.erb

<div id="countdown-package">
<div id="countdown" class="timer"></div>
<div id="force-note">
<h4>days</h4>
<h4>hours</h4>
<h4>minutes</h4>
<h4>seconds</4>
</div>
</div>


app/views/shared/_header.html.erb


<nav>
<ul>
<li><%= link_to "Home", root_path, class: "main-nav-link silver-fade" %></li>
<li><%= link_to "Our Story", story_path, class: "main-nav-link silver-fade" %></li>
<li><%= link_to "Invitation", invite_path, class: "main-nav-link silver-fade" %></li>
<li><%= link_to "Pictures", pictures_path, class: "main-nav-link silver-fade" %></li>
<li><%= link_to "Wishes", wish_path, class: "main-nav-link silver-fade" %></li>
<li><%= link_to "Live", live_path, class: "main-nav-link silver-fade" %></li>
</ul>
</nav>

<div id="admin-nav">
<% if admin_signed_in? %>
	<%= link_to "Sign out", destroy_admin_session_path, :method => :delete, id: "admin_sign_out"%>
	<%= link_to "Index", guests_path, id: "admin_index"%>
<% else %>
	<%= link_to "Admin", new_admin_session_path, id: "admin_sign_in"%>
<% end %>
</div>


app/views/static_pages/_wishbox.html.erb
<h4><%= @guest.wish %></h4>
<p><strong>- <%= @guest.name%></strong></p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div id="container">
<div id="topHalf">

<%= image_tag("her_and_me.png", id: "mainImage", alt: "Her and me", class: "lifted") %>
<div id="wish_box"></div>

</div>

<div id="bottomHalf">

<div id="verse-2" >
<h2>"For I know the thoughts that I think toward you, says the Lord, thoughts of peace and not of evil, to give you a future and a hope."
- Jer 29:11</h2>
</div>

<div id="hidden_text"></div>

</div>

</div>

app/views/static_pages/invite.html.erb
<% provide(:title, "Invitation") %>

<div id="container">
<div id="invitation-wrapper">
<%= image_tag("invitation-2.png", id: "invitation") %>
</div>
</div>

app/views/static_pages/live.html.erb
<% provide(:title, "Live") %>

<div id="container">
<div id="verse-2">
<h4>This event has concluded. Thank you for all your good wishes!</h4>
</div>
</div>

app/views/static_pages/pictures.html.erb
<% provide(:title, "Gallery") %>


<div id="container">
<div id="gallery">
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_ma_and_paa.jpg", alt: "With his family")), "https://s3-us-west-2.amazonaws.com/josteffgallery/maa_and_paa.JPG" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_everyone.jpg", alt: "All of us")), "https://s3-us-west-2.amazonaws.com/josteffgallery/everyone.JPG" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_us.jpg", alt: "Right after the ceremony")), "https://s3-us-west-2.amazonaws.com/josteffgallery/just_us.JPG" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_with_becky.jpg", alt: "With Becky :)")), "https://s3-us-west-2.amazonaws.com/josteffgallery/with_becky.JPG" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_1.jpg", alt: "Our personal favorite! <3")), "https://s3-us-west-2.amazonaws.com/josteffgallery/1.JPG" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_2.jpg", alt: "Just the siblings")), "https://s3-us-west-2.amazonaws.com/josteffgallery/2.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_3.jpg", alt: "With her family")), "https://s3-us-west-2.amazonaws.com/josteffgallery/3.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_4.jpg", alt: "The dads shaking hands")), "https://s3-us-west-2.amazonaws.com/josteffgallery/4.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_5.jpg", alt: "The dads shaking hands some more")), "https://s3-us-west-2.amazonaws.com/josteffgallery/5.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_6.jpg", alt: "The dads hugging!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/6.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_7.jpg", alt: "Praying - you won't catch us with our eyes open!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/7.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_8.jpg", alt: "Impromptu speech!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/8.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_9.jpg", alt: "Competing with her in the smiles department")), "https://s3-us-west-2.amazonaws.com/josteffgallery/9.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_10.jpg", alt: "With her siblings")), "https://s3-us-west-2.amazonaws.com/josteffgallery/10.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_11.jpg", alt: "One for the ages!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/11.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_12.jpg", alt: "Cover photo!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/12.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_13.jpg", alt: "Loving the proximity!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/13.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_14.jpg")), "https://s3-us-west-2.amazonaws.com/josteffgallery/14.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_15.jpg", alt: "The stage is set")), "https://s3-us-west-2.amazonaws.com/josteffgallery/15.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_16.jpg")), "https://s3-us-west-2.amazonaws.com/josteffgallery/16.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_17.jpg", alt: "The dinner venue")), "https://s3-us-west-2.amazonaws.com/josteffgallery/17.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_18.jpg", alt: "The approach")), "https://s3-us-west-2.amazonaws.com/josteffgallery/18.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_19.jpg", alt: "The choir")), "https://s3-us-west-2.amazonaws.com/josteffgallery/19.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_20.jpg", alt: "All smiles!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/20.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_21.jpg", alt: "Stately")), "https://s3-us-west-2.amazonaws.com/josteffgallery/21.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_22.jpg", alt: "His Ammachi (Grandma) being funny!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/22.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_23.jpg", alt: "Double hug from uncle DP")), "https://s3-us-west-2.amazonaws.com/josteffgallery/23.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_24.jpg", alt: "Her Ammachi (Grandma) being funny!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/24.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_25.jpg", alt: "With Stelcy :)")), "https://s3-us-west-2.amazonaws.com/josteffgallery/25.jpg" %>
<%= link_to (image_tag("https://s3-us-west-2.amazonaws.com/josteffgallery/thumb_26.jpg", alt: "Another one for the ages!")), "https://s3-us-west-2.amazonaws.com/josteffgallery/26.jpg" %>

</div>
<div id="verse-2" >
<h4>" ... when He had by Himself purged our sins, sat down on the right hand of the Majesty on high"<br> - Heb 1:3</h4>
</div>


app/views/static_pages/story.html.erb
<% provide(:title, "Our Story") %>

<div id="container">
<div id="story">
<h4>… Because the love of God has been poured out in our hearts …<br />
-	Romans  5:5(Bible)<br /><br />
We firmly believe that God the Grand Weaver has woven the threads of our lives together with the golden strands of marriage. As we are united in the 
bond of marriage we can’t help but be amazed at our Heavenly Father’s intricate design in making our lives one. But what amazes us 
even more everyday is the saving grace of God that has made fallen creatures like us His children. The Bible says that everyone in 
this world is ‘dead to God in their sin’ and yet God loved the world enough to send His one and only Son the Lord Jesus to die 
for our sin. Faith in Him alone will relieve you from the guilt and consequence of sin and make you ‘alive to God’. We are extremely 
grateful to God that He has helped us realize this in our lives and we extend this invitation to you to accept the Lord Jesus as your 
Saviour today.
</h4>
</div>
</div>
<div id="verse-2" >
<h4>"As for God, His way is perfect;<br>The word of the Lord is proven;<br>
He is a shield to all who trust in Him.<br> - Psalm 18:30</h4>
</div>

app/views/static_pages/wish.html.erb
<% provide(:title, 'Wedding Wishes') %>



<h1>Wedding Wishes</h1>